name: builder

on:
  push:
    branches: [master]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
    - uses: actions/checkout@v2
    - name: depends
      run: sudo apt-get install -y libsdl1.2-dev libsdl-image1.2-dev libsdl-mixer1.2-dev
    - name: configure
      run: ./config.sh
    - name: update makefile
      run: make gnu
    - name: make
      run: make
    outputs:
        binary: brillion
